[workspace]
members = ["projects/*"]
default-members = [
    "projects/qr-image-core",
    "projects/qr-image-cli",
    "projects/qr-image-web",
]

exclude = [
    "projects/.DS_Store",
    "projects/qr-image-wolfram",
]

[profile.release]
lto = true
panic = "abort"